### ISSUE TITLE
Doesn't work for 2016S

### ISSUE THREAD

**Issue by benwaffle** [joshgrib/sitstuff#11]

**Comment by joshgrib** [comment]
@benwaffle Worked for my classes - what ones are you entering?

**Comment by joshgrib** [comment]
Also I forgot to push the 2016 update to github, but it was on the server. Just commited

**Comment by benwaffle** [comment]
CS182, CS135, PEP112, PEP221, CAL105, MA222

**Comment by joshgrib** [comment]
PEP 112 is causing an internal server error
CS 135 is causing a 403 forbidden error, and saying "CSRF verification failed. Request aborted."

For the internal service error, the server should be running on debug mode, but it's not giving the error messages for whatever reason. I ran it locally and PEP 112 has a keyerror for "Day", even thought the XML for that course and other ones don't seem different

```
<Course Section="PEP 112S" Title="Electricity & Magnetism" CallNumber="11658" MinCredit="3" MaxCredit="3" MaxEnrollment="25" CurrentEnrollment="0" Status="O" StartDate="2016-01-19Z" EndDate="2016-05-17Z" Instructor1="STAFF" Term="2016S">
<Meeting Day="MR" StartTime="9:00:00Z" EndTime="10:40:00Z" Site="Castle Point" Building="B" Room="714" Activity="LEC"/>
<Requirement Control="RQ" Argument="" Value1="PEP 111" Operator="" Value2=""/>
<Requirement Control="R&" Argument="" Value1="MA 115" Operator="" Value2="MA 122"/>
<Requirement Control="CS" Argument="" Value1="D 110C" Operator="" Value2=""/>
</Course>
<Course Section="PEP 124A" Title="Physics for B&T II" CallNumber="11659" MinCredit="3" MaxCredit="3" MaxEnrollment="50" CurrentEnrollment="0" Status="O" StartDate="2016-01-19Z" EndDate="2016-05-17Z" Instructor1="Sikand M" Term="2016S">
<Meeting Day="TF" StartTime="4:00:00Z" EndTime="4:50:00Z" Site="Castle Point" Building="P" Room="116" Activity="LEC"/>
<Requirement Control="RQ" Argument="" Value1="PEP 123" Operator="" Value2="PEP 111"/>
<Requirement Control="CA" Argument="" Value1="LAB" Operator="" Value2=""/>
<Requirement Control="CS" Argument="" Value1="D 110C" Operator="" Value2=""/>
</Course>
```

I have no idea what CS 135 is doing, sometimes it just doesn't schedule, sometimes its the only thing that gets scheduled. The XML for that seems normal too

**Comment by benwaffle** [comment]
221 is the lab for 112
could that be the problem

**Comment by joshgrib** [comment]
Yeah it might be that then. Most labs are just the number with an "L", but the XML for that seems find too, so I'm not sure what the specific problem would be
